const $=id=>document.getElementById(id), profiles=window.KAIREN_PROFILES;
let lastUrl=null,lastBlob=null;
Object.values(profiles).forEach(p=>{const o=document.createElement("option");o.value=p.id;o.textContent=p.name;$("profile").appendChild(o)});
for(let i=1;i<=11;i++){const o=document.createElement("option");o.value=String(i).padStart(2,"0");o.textContent=o.value;$("heightIn").appendChild(o)}
$("profile").value="CO"; $("addressState").value="CO"; applyProfile();

function applyProfile(){const p=profiles[$("profile").value];$("profileNote").textContent=p.note;const w=$("inventoryWrap");w.style.display=p.inventory.enabled?"flex":"none";$("inventory").maxLength=p.inventory.length||50;}
function collect(){return{profile:$("profile").value,data:{firstName:$("firstName").value.trim().toUpperCase(),middleName:$("middleName").value.trim().toUpperCase(),lastName:$("lastName").value.trim().toUpperCase(),dln:$("dln").value.trim().toUpperCase(),dob:$("dob").value.trim(),iss:$("iss").value.trim(),exp:$("exp").value.trim(),sex:$("sex").value,heightFt:$("heightFt").value,heightIn:$("heightIn").value,eye:$("eye").value,dd:$("dd").value.trim().toUpperCase(),inventory:$("inventory").value.trim().toUpperCase(),street:$("street").value.trim().toUpperCase(),city:$("city").value.trim().toUpperCase(),addressState:$("addressState").value.trim().toUpperCase(),zip:$("zip").value.trim()}}}
async function generate(){try{const p=collect();if(!p.data.firstName||!p.data.lastName||!p.data.dln)throw Error("Faltan Nombre, Apellido o DLN/Folio.");$("generate").disabled=true;$("generate").textContent="Generando...";const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});if(!r.ok)throw Error(await r.text());lastBlob=await r.blob();if(lastUrl)URL.revokeObjectURL(lastUrl);lastUrl=URL.createObjectURL(lastBlob);$("preview").innerHTML=`<img src="${lastUrl}" alt="PDF417">`;$("download").disabled=false}catch(e){alert(e.message)}finally{$("generate").disabled=false;$("generate").textContent="Generar PDF417 de prueba"}}
function demo(){Object.assign($("firstName"),{value:"JOURDAN"});$("middleName").value="ELIZA";$("lastName").value="SULLIVAN";$("dln").value="FORM-000123";$("dob").value="09/22/1992";$("iss").value="02/13/2024";$("exp").value="02/13/2032";$("sex").value="F";$("heightFt").value="5";$("heightIn").value="07";$("eye").value="BRO";$("dd").value="TESTDD001";$("inventory").value=$("profile").value==="CO"?"C0004884992":"TEST0000001";$("street").value="20662 DUKE";$("city").value="AURORA";$("addressState").value=$("profile").value;$("zip").value="80013";}
$("profile").onchange=applyProfile;$("generate").onclick=generate;$("fillDemo").onclick=demo;$("clear").onclick=()=>location.reload();
$("download").onclick=()=>{if(!lastUrl)return;const a=document.createElement("a");a.href=lastUrl;a.download=`kairen_${$("profile").value}_pdf417_test.png`;a.click()};
$("copyPayload").onclick=async()=>{const t=JSON.stringify(collect(),null,2);try{await navigator.clipboard.writeText(t)}catch{prompt("Copia los datos:",t)}};
