window.KAIREN_PROFILES = {
  AL: { id:"AL", name:"Alabama (AL)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  AK: { id:"AK", name:"Alaska (AK)", ready:true, note:"Alaska V10 / referencia 2020 configurado con IIN 636059 y el orden de campos del ejemplo proporcionado. DDE/DDF/DDG quedan manuales para respetar el payload suministrado.", version:"10", subfile:"DL", strictDefault:true, dateFormat:"MMDDYYYY", heightFormat:"IN", iin:"636059", jurisdictionVersion:"00", autoTruncation:false },
  AZ: { id:"AZ", name:"Arizona (AZ)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL", strictDefault:false, dateFormat:"MMDDYYYY", heightFormat:"IN" },
  AR: { id:"AR", name:"Arkansas (AR)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  CA: { id:"CA", name:"California (CA)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  CO: { id:"CO", name:"Colorado (CO)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL", strictDefault:true },
  CT: { id:"CT", name:"Connecticut (CT)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  DE: { id:"DE", name:"Delaware (DE)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  DC: { id:"DC", name:"District of Columbia (DC)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  FL: { id:"FL", name:"Florida (FL)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  GA: { id:"GA", name:"Georgia (GA)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  HI: { id:"HI", name:"Hawaii (HI)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  ID: { id:"ID", name:"Idaho (ID)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  IL: { id:"IL", name:"Illinois (IL)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  IN: { id:"IN", name:"Indiana (IN)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  IA: { id:"IA", name:"Iowa (IA)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  KS: { id:"KS", name:"Kansas (KS)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  KY: { id:"KY", name:"Kentucky (KY)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  LA: { id:"LA", name:"Louisiana (LA)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  ME: { id:"ME", name:"Maine (ME)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  MD: { id:"MD", name:"Maryland (MD)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  MA: { id:"MA", name:"Massachusetts (MA)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  MI: { id:"MI", name:"Michigan (MI)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  MN: { id:"MN", name:"Minnesota (MN)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  MS: { id:"MS", name:"Mississippi (MS)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  MO: { id:"MO", name:"Missouri (MO)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  MT: { id:"MT", name:"Montana (MT)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  NE: { id:"NE", name:"Nebraska (NE)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  NV: { id:"NV", name:"Nevada (NV)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  NH: { id:"NH", name:"New Hampshire (NH)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  NJ: { id:"NJ", name:"New Jersey (NJ)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  NM: { id:"NM", name:"New Mexico (NM)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  NY: { id:"NY", name:"New York (NY)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  NC: { id:"NC", name:"North Carolina (NC)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  ND: { id:"ND", name:"North Dakota (ND)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  OH: { id:"OH", name:"Ohio (OH)", ready:true, note:"Ohio V10 / AAMVA 2020 configurado con el IIN 636023 y el orden de campos del ejemplo proporcionado. DDE/DDF/DDG quedan manuales para respetar exactamente el payload de Ohio.", version:"10", subfile:"DL", strictDefault:true, dateFormat:"MMDDYYYY", heightFormat:"IN", iin:"636023", jurisdictionVersion:"00", autoTruncation:false },
  OK: { id:"OK", name:"Oklahoma (OK)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  OR: { id:"OR", name:"Oregon (OR)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  PA: { id:"PA", name:"Pennsylvania (PA)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  RI: { id:"RI", name:"Rhode Island (RI)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  SC: { id:"SC", name:"South Carolina (SC)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  SD: { id:"SD", name:"South Dakota (SD)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  TN: { id:"TN", name:"Tennessee (TN)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  TX: { id:"TX", name:"Texas (TX)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  UT: { id:"UT", name:"Utah (UT)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  VT: { id:"VT", name:"Vermont (VT)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  VA: { id:"VA", name:"Virginia (VA)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  WA: { id:"WA", name:"Washington (WA)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  WV: { id:"WV", name:"West Virginia (WV)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  WI: { id:"WI", name:"Wisconsin (WI)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" },
  WY: { id:"WY", name:"Wyoming (WY)", ready:true, note:"Perfil disponible para payload interno de prueba. No representa codificación oficial de una jurisdicción.", version:"10", subfile:"DL" }
};
