window.KAIREN_PROFILES = {
  AL: { id:"AL", name:"Alabama (AL)", ready:false, note:"Perfil Alabama gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  AK: { id:"AK", name:"Alaska (AK)", ready:false, note:"Perfil Alaska creado; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  AZ: { id:"AZ", name:"Arizona (AZ)", ready:true, note:"AZ V10: DCL no se codifica; se mantiene fuera del formulario/payload. Perfil Arizona cargado.", version:"10", subfile:"DL", strictDefault:false, dateFormat:"MMDDYYYY", heightFormat:"IN" },
  AR: { id:"AR", name:"Arkansas (AR)", ready:false, note:"Perfil Arkansas gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  CA: { id:"CA", name:"California (CA)", ready:false, note:"Perfil California gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  CO: { id:"CO", name:"Colorado (CO)", ready:true, note:"Perfil Colorado completo para el formulario.", version:"10", subfile:"DL", strictDefault:true },
  CT: { id:"CT", name:"Connecticut (CT)", ready:false, note:"Perfil Connecticut gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  DE: { id:"DE", name:"Delaware (DE)", ready:false, note:"Perfil Delaware gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  DC: { id:"DC", name:"District of Columbia (DC)", ready:false, note:"Perfil District of Columbia gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  FL: { id:"FL", name:"Florida (FL)", ready:false, note:"Perfil Florida gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  GA: { id:"GA", name:"Georgia (GA)", ready:false, note:"Perfil Georgia gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  HI: { id:"HI", name:"Hawaii (HI)", ready:false, note:"Perfil Hawaii gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  ID: { id:"ID", name:"Idaho (ID)", ready:false, note:"Perfil Idaho gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  IL: { id:"IL", name:"Illinois (IL)", ready:false, note:"Perfil Illinois gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  IN: { id:"IN", name:"Indiana (IN)", ready:false, note:"Perfil Indiana creado; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  IA: { id:"IA", name:"Iowa (IA)", ready:false, note:"Perfil Iowa gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  KS: { id:"KS", name:"Kansas (KS)", ready:false, note:"Perfil Kansas gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  KY: { id:"KY", name:"Kentucky (KY)", ready:false, note:"Perfil Kentucky gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  LA: { id:"LA", name:"Louisiana (LA)", ready:false, note:"Perfil Louisiana gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  ME: { id:"ME", name:"Maine (ME)", ready:false, note:"Perfil Maine gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  MD: { id:"MD", name:"Maryland (MD)", ready:false, note:"Perfil Maryland gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  MA: { id:"MA", name:"Massachusetts (MA)", ready:false, note:"Perfil Massachusetts gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  MI: { id:"MI", name:"Michigan (MI)", ready:false, note:"Perfil Michigan gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  MN: { id:"MN", name:"Minnesota (MN)", ready:false, note:"Perfil Minnesota gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  MS: { id:"MS", name:"Mississippi (MS)", ready:false, note:"Perfil Mississippi gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  MO: { id:"MO", name:"Missouri (MO)", ready:false, note:"Perfil Missouri gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  MT: { id:"MT", name:"Montana (MT)", ready:false, note:"Perfil Montana gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  NE: { id:"NE", name:"Nebraska (NE)", ready:false, note:"Perfil Nebraska gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  NV: { id:"NV", name:"Nevada (NV)", ready:false, note:"Perfil Nevada gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  NH: { id:"NH", name:"New Hampshire (NH)", ready:false, note:"Perfil New Hampshire gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  NJ: { id:"NJ", name:"New Jersey (NJ)", ready:false, note:"Perfil New Jersey gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  NM: { id:"NM", name:"New Mexico (NM)", ready:false, note:"Perfil New Mexico gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  NY: { id:"NY", name:"New York (NY)", ready:false, note:"Perfil New York gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  NC: { id:"NC", name:"North Carolina (NC)", ready:false, note:"Perfil North Carolina gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  ND: { id:"ND", name:"North Dakota (ND)", ready:false, note:"Perfil North Dakota gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  OH: { id:"OH", name:"Ohio (OH)", ready:false, note:"Perfil Ohio gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  OK: { id:"OK", name:"Oklahoma (OK)", ready:false, note:"Perfil Oklahoma gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  OR: { id:"OR", name:"Oregon (OR)", ready:false, note:"Perfil Oregon gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  PA: { id:"PA", name:"Pennsylvania (PA)", ready:false, note:"Perfil Pennsylvania gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  RI: { id:"RI", name:"Rhode Island (RI)", ready:false, note:"Perfil Rhode Island gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  SC: { id:"SC", name:"South Carolina (SC)", ready:false, note:"Perfil South Carolina gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  SD: { id:"SD", name:"South Dakota (SD)", ready:false, note:"Perfil South Dakota gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  TN: { id:"TN", name:"Tennessee (TN)", ready:false, note:"Perfil Tennessee gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  TX: { id:"TX", name:"Texas (TX)", ready:false, note:"Perfil Texas gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  UT: { id:"UT", name:"Utah (UT)", ready:false, note:"Perfil Utah gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  VT: { id:"VT", name:"Vermont (VT)", ready:false, note:"Perfil Vermont gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  VA: { id:"VA", name:"Virginia (VA)", ready:false, note:"Perfil Virginia gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  WA: { id:"WA", name:"Washington (WA)", ready:false, note:"Perfil Washington gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  WV: { id:"WV", name:"West Virginia (WV)", ready:false, note:"Perfil West Virginia gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  WI: { id:"WI", name:"Wisconsin (WI)", ready:false, note:"Perfil Wisconsin gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" },
  WY: { id:"WY", name:"Wyoming (WY)", ready:false, note:"Perfil Wyoming gen\u00e9rico; reglas espec\u00edficas pendientes.", version:"10", subfile:"DL" }
};
